"""Original stylish bio templates inspired by public name/bio design patterns."""

BIOS = [
    "ᥫ᭡ {n} — soft heart, sharp mind ✦",
    "𓆩♡𓆪 {small} | made of dreams & late nights 🌙",
    "🦋 {small} • quietly becoming my best version ✨",
    "🌸 {n} | peace in the heart, fire in the soul 🔥",
    "꒰ঌ {small} ໒꒱ | lost in little beautiful things 🫧",
    "🎀 {small} — sweet outside, savage by choice 🖤",
    "🧿 {n} | nazar se door • goals se close 🎯",
    "☾ {small} | romanticizing my own life ✧",
    "💎 {n} • rare energy, simple living 🤍",
    "🌙 {small} | midnight thoughts & golden dreams ✨",
    "🪷 {n} | calm soul, loud dreams 💫",
    "𓂃 ࣪˖ {small} ˚₊‧ | just vibes 🎧",
    "♡ {n} | choosing peace over proving points 🕊️",
    "⚡ {small} | focused, fearless, unfinished 🚀",
    "🌿 {n} • growing through what I go through 🌱",
    "🦋 𝓛𝓲𝓯𝓮 𝓫𝔂 {small} | no copy, only original 💫",
    "👑 {n} | standards high, circle small 🖤",
    "✨ {small} | a little chaos, a lot of magic 🪄",
    "🌹 {n} • heart full of stories, eyes full of stars 🌌",
    "🎧 {small} | music on • world off 🎶",
    "🫧 {small} | soft soul with a strong boundary 🤍",
    "𓆩🔥𓆪 {n} | built from pressure, powered by purpose",
    "💗 {small} | love softly, live loudly, leave kindly",
    "🌙 {n} | moonlight mind • sunrise heart ☀️",
    "🖤 {small} | not cold, just selective 🥀",
    "🍃 {n} | less noise • more life • more peace",
    "🪽 {small} | protecting my peace like it's sacred ✨",
    "💫 {n} | ordinary days, extraordinary mindset",
    "🌸 {small} | pretty mind • peaceful life • pure energy",
    "⚜️ {n} | class in silence, power in patience",
    "🪐 {small} | somewhere between reality & daydreams ☁️",
    "🎀 {n} | cute face • dangerous confidence 😌",
    "🧿 {small} | good vibes only, bad energy blocked 🚫",
    "🔥 {n} | no shortcuts • no excuses • no regrets",
    "🦢 {small} | graceful outside, unstoppable inside",
    "🤍 {n} | kindness is my flex ✨",
    "🌷 {small} | blooming at my own speed ⏳",
    "👀 {n} | private life • peaceful mind • loud goals",
    "☕ {small} | caffeine, confidence & calm mornings",
    "🎵 {n} | life hits different with the right playlist",
    "🫶 {small} | real over perfect, always",
    "💎 {n} | energy expensive, access limited 🔒",
    "🌙 {small} | silent nights know my loudest dreams",
    "🖤 {n} | loyalty rare • silence powerful",
    "🪷 {small} | soft words, strong standards",
    "⚡ {n} | discipline today • freedom tomorrow",
    "🌿 {small} | becoming someone my younger self would admire",
    "🦋 {n} | changing, healing, glowing ✨",
    "🥀 {small} | some chapters need no explanation",
    "🎧 {n} | headphones on, distractions gone",
    "🚩 {small} | desi heart • independent mind 🇮🇳",
    "👑 {n} | self-respect first, everything else later",
    "🫧 {small} | collecting moments, not opinions",
    "🌹 {n} | too busy building the life I imagined",
    "✨ {small} | main character energy, quiet edition",
    "🕊️ {n} | forgive, grow, move forward",
    "🔥 {small} | pressure made me sharper, not bitter",
    "💗 {n} | heart soft • boundaries hard",
    "🌌 {small} | dreaming beyond the obvious",
    "🪩 {n} | a little sparkle never hurt ✨",
    "🍂 {small} | changing seasons, changing me",
    "🖇️ {n} | attached to peace, detached from drama",
    "🧸 {small} | sweet soul, serious goals",
    "💫 {n} | trust the timing • keep moving",
    "🌸 {small} | private smiles, public silence",
    "🖤 {n} | I don't chase, I attract",
    "🎀 {small} | soft aesthetic • strong mindset",
    "⚜️ {n} | elegance is an attitude",
    "☁️ {small} | somewhere between coffee and clouds",
    "🌙 {n} | nights taught me things daylight couldn't",
    "🦋 {small} | healing looks good on me",
    "🪷 {n} | peace is the new flex",
    "🔥 {small} | born to stand out, not fit in",
    "🧿 {n} | protected energy • selective access",
    "💎 {small} | rare doesn't mean loud",
    "🎧 {n} | mood: music + silence",
    "🌿 {small} | slow progress is still progress",
    "👑 {n} | confidence without announcement",
    "🤍 {small} | love life • love self • love growth",
    "🪽 {n} | leaving what no longer feels like home",
    "✨ {small} | tiny steps, huge dreams",
    "🌹 {n} | romantic soul, realistic mind",
    "🪐 {small} | not lost, just exploring",
    "⚡ {n} | calm face, competitive spirit",
    "🫶 {small} | good heart, clear limits",
    "🥀 {n} | beautiful things take time",
    "🍃 {small} | breathe • believe • become",
    "🎶 {n} | soundtrack of my own story",
    "🦢 {small} | move with grace, think with courage",
    "🌸 {n} | today's peace is tomorrow's strength",
    "💖 {small} | made with love, powered by hope",
    "🔒 {n} | private person, public dreams",
    "🌙 {small} | after dark, ideas shine brighter",
    "🔥 {n} | ambition with a soft heart",
    "🖤 {small} | no drama, just standards",
    "🫧 {n} | keeping life light and meaningful",
    "🌷 {small} | growing quietly, glowing loudly",
    "🎀 {n} | pretty vibes, powerful mind",
    "🧿 {small} | nazar off • focus on ✅",
    "👑 {n} | built different, staying humble",
    "💫 {small} | one life • make it beautiful",
]
